<html>
    <style>
        body{
            background-color:blue;
        }
        h1{
            color:red;
        }
        </style>
        <body>
            <h1>helloo</h1>
        </body>
        <html>